In [1]:
# Import libraries
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

# Create a dataset

value_y_list = [78.5, 74.3, 104.3, 87.6, 95.9, 109.2, 102.7, 72.5, 93.1, 115.9, 83.8, 113.3, 109.4] # valores de Y
value_x1_list = [7, 1, 11, 11, 7, 11, 3, 1, 2, 21, 1, 11, 10] # valores de X1
value_x2_list = [26, 29, 56, 31, 52, 55, 71, 31, 54, 47, 40, 66, 68] # valores de X2
value_x3_list = [6, 15, 8, 8, 6, 9, 17, 22, 18, 4, 23, 9, 8] # valores de X3
value_x4_list = [60, 52, 20, 47, 33, 22, 6, 44, 22, 26, 34, 12, 12] # valores de X4

data_dict = {"Y":value_y_list,
             "X1":value_x1_list,
             "X2":value_x2_list,
             "X3":value_x3_list,
             "X4":value_x4_list}

print(data_dict)

# Turn a dictionary into a dataframe
df = pd.DataFrame(data_dict)

#print(df) Tabla básica
df

{'Y': [78.5, 74.3, 104.3, 87.6, 95.9, 109.2, 102.7, 72.5, 93.1, 115.9, 83.8, 113.3, 109.4], 'X1': [7, 1, 11, 11, 7, 11, 3, 1, 2, 21, 1, 11, 10], 'X2': [26, 29, 56, 31, 52, 55, 71, 31, 54, 47, 40, 66, 68], 'X3': [6, 15, 8, 8, 6, 9, 17, 22, 18, 4, 23, 9, 8], 'X4': [60, 52, 20, 47, 33, 22, 6, 44, 22, 26, 34, 12, 12]}


,Y,X1,X2,X3,X4
0,78.5,7,26,6,60
1,74.3,1,29,15,52
2,104.3,11,56,8,20
3,87.6,11,31,8,47
4,95.9,7,52,6,33
5,109.2,11,55,9,22
6,102.7,3,71,17,6
7,72.5,1,31,22,44
8,93.1,2,54,18,22
9,115.9,21,47,4,26


In [2]:
import numpy as np

# Convertir el DataFrame a una matriz NumPy
matrix = df.to_numpy()

# Crear una columna de unos con el mismo número de filas que la matriz
ones_column = np.ones((matrix.shape[0], 1))

# Reemplazar la primera columna de la matriz con la columna de unos
matrix_with_ones = np.concatenate((ones_column, matrix[:, 1:]), axis=1)

# Mostrar la matriz resultante
print("Matriz original (primeras 5 filas):\n", matrix[:5])
print("\nMatriz con la primera columna reemplazada por unos (primeras 5 filas):\n", matrix_with_ones[:5])

Matriz original (primeras 5 filas):
 [[ 78.5   7.   26.    6.   60. ]
 [ 74.3   1.   29.   15.   52. ]
 [104.3  11.   56.    8.   20. ]
 [ 87.6  11.   31.    8.   47. ]
 [ 95.9   7.   52.    6.   33. ]]

Matriz con la primera columna reemplazada por unos (primeras 5 filas):
 [[ 1.  7. 26.  6. 60.]
 [ 1.  1. 29. 15. 52.]
 [ 1. 11. 56.  8. 20.]
 [ 1. 11. 31.  8. 47.]
 [ 1.  7. 52.  6. 33.]]


In [3]:
# Calcular la matriz transpuesta
transposed_matrix = matrix_with_ones.T

# Mostrar la matriz transpuesta
print("Matriz transpuesta (primeras 5 filas):\n", transposed_matrix[:5])

Matriz transpuesta (primeras 5 filas):
 [[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 7.  1. 11. 11.  7. 11.  3.  1.  2. 21.  1. 11. 10.]
 [26. 29. 56. 31. 52. 55. 71. 31. 54. 47. 40. 66. 68.]
 [ 6. 15.  8.  8.  6.  9. 17. 22. 18.  4. 23.  9.  8.]
 [60. 52. 20. 47. 33. 22.  6. 44. 22. 26. 34. 12. 12.]]


In [4]:
# Extraer la columna 'Y' del DataFrame original
Y_column_df = df['Y']

# Convertir la columna 'Y' a un vector NumPy
Y_vector = Y_column_df.to_numpy()

# Mostrar el vector resultante y su forma
print("Columna 'Y' como DataFrame:\n", Y_column_df)
print("\nVector 'Y' (primeras 5 filas):\n", Y_vector[:5])
print("\nForma del vector 'Y':", Y_vector.shape)

Columna 'Y' como DataFrame:
 0      78.5
1      74.3
2     104.3
3      87.6
4      95.9
5     109.2
6     102.7
7      72.5
8      93.1
9     115.9
10     83.8
11    113.3
12    109.4
Name: Y, dtype: float64

Vector 'Y' (primeras 5 filas):
 [ 78.5  74.3 104.3  87.6  95.9]

Forma del vector 'Y': (13,)


In [5]:
# Multiplicar la matriz transpuesta por la matriz original con unos
# Usamos np.dot para la multiplicación de matrices
multiplied_matrix = np.dot(transposed_matrix, matrix_with_ones)

# Mostrar la matriz resultante y su forma
print("Matriz multiplicada (primeras 5 filas y columnas):\n", multiplied_matrix[:5, :5])
print("\nForma de la matriz multiplicada:", multiplied_matrix.shape)

Matriz multiplicada (primeras 5 filas y columnas):
 [[1.3000e+01 9.7000e+01 6.2600e+02 1.5300e+02 3.9000e+02]
 [9.7000e+01 1.1390e+03 4.9220e+03 7.6900e+02 2.6200e+03]
 [6.2600e+02 4.9220e+03 3.3050e+04 7.2010e+03 1.5739e+04]
 [1.5300e+02 7.6900e+02 7.2010e+03 2.2930e+03 4.6280e+03]
 [3.9000e+02 2.6200e+03 1.5739e+04 4.6280e+03 1.5062e+04]]

Forma de la matriz multiplicada: (5, 5)


In [6]:
# Calcular la inversa de la matriz multiplicada
# Asegúrate de que la matriz sea cuadrada e invertible para evitar errores
inverse_multiplied_matrix = np.linalg.inv(multiplied_matrix)

# Mostrar la matriz inversa resultante y su forma
print("Matriz inversa (primeras 5 filas y columnas):\n", inverse_multiplied_matrix[:5, :5])
print("\nForma de la matriz inversa:", inverse_multiplied_matrix.shape)

Matriz inversa (primeras 5 filas y columnas):
 [[ 8.20654575e+02 -8.44180186e+00 -8.45777985e+00 -8.63453878e+00
  -8.28974378e+00]
 [-8.44180186e+00  9.27104019e-02  8.56862094e-02  9.26373566e-02
   8.44549553e-02]
 [-8.45777985e+00  8.56862094e-02  8.75602572e-02  8.78666397e-02
   8.55980995e-02]
 [-8.63453878e+00  9.26373566e-02  8.78666397e-02  9.52014097e-02
   8.63919188e-02]
 [-8.28974378e+00  8.44549553e-02  8.55980995e-02  8.63919188e-02
   8.40311912e-02]]

Forma de la matriz inversa: (5, 5)


In [7]:
import numpy as np

# Multiplicar la matriz inversa por la matriz transpuesta
step1_multiplication = np.dot(inverse_multiplied_matrix, transposed_matrix)

# Multiplicar el resultado del paso 1 por el vector Y
beta_coefficients = np.dot(step1_multiplication, Y_vector)

# Mostrar los coeficientes beta resultantes y su forma
print("Coeficientes beta:", beta_coefficients)
print("Forma de los coeficientes beta:", beta_coefficients.shape)

Coeficientes beta: [62.4053693   1.55110265  0.51016758  0.1019094  -0.14406103]
Forma de los coeficientes beta: (5,)
